[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
test = 'test'
script = 'script'
cache_path  = 'cache_forge'
solc = '0.8.25'
optimizer = true
optimizer-runs = 10_000_000
fs_permissions = [{ access = "read-write", path = "./data" }]
auto_detect_remappings = false

[profile.ci.fuzz]
runs = 10_000
